version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  model:
    build: ./inference
    container_name: inference_container
    environment:
      MODEL_WEIGHTS_PATH: ${MODEL_WEIGHTS_PATH}
      TOKENIZER_PATH: ${TOKENIZER_PATH}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgresdb:
    build: ./db_
    container_name: db_saver
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_container
    environment:
      MODEL_SERVICE_URL: http://model:8000
      DBSAVER_SERVICE_URL: http://dbsaver:8080
    ports:
      - "8501:8501"
    depends_on:
      - model
      - dbsaver

volumes:
  postgres_data: